### PR TITLE
Add verify email

### PR DESCRIPTION
**Pull request by vishnu-sagubandi**

### CODE REVIEW

**Comment by vishnu-sagubandi** [comment]
Environmental variables need to declared:

1. `EMAIL_ID` = Email host user
2. `EMAIL_PASS` = 2-step verification and Application specific password

**Comment by raghavTinker** [comment]
Minor issue in the ```views.py``` file in the users app. The ```from_email``` while invoking function ```send_verify_email``` has been set to the user's name rather than the host's email. Please rectify that.

```
 send_verify_email(to_mail=to_mail, 
                   from_mail=settings.EMAIL_HOST_USER, 
                   verify_link=verify_link)
```
Otherwise, an excellent job!!👍

**Comment by vishnu-sagubandi** [comment]
> Minor issue in the `views.py` file in the users app. The `from_email` while invoking function `send_verify_email` has been set to the user's name rather than the host's email. Please rectify that.
> 
> ```
>  send_verify_email(to_mail=to_mail, 
>                    from_mail=settings.EMAIL_HOST_USER, 
>                    verify_link=verify_link)
> ```
> 
> Otherwise, an excellent job!!👍

Done👍. Thank you 😊 .

**Review by raghavTinker — APPROVED** [review]
Great job!!

**Pull request merged**
